#!/usr/bin/env node
import esbuild from 'esbuild';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const commonBuildOptions = {
  bundle: true,
  format: 'iife',
  platform: 'browser',
  minify: false,
  sourcemap: false,
  external: [],
  loader: {
    '.js': 'js',
    '.wasm': 'file',
  },
  define: {
    'process.env.NODE_ENV': '"production"',
    'import.meta.url': '"https://localhost:3000/"',
  },
  banner: {
    js: `
// Worker bundle generated by esbuild
// Polyfill for import.meta.url
if (typeof globalThis.importMetaUrl === 'undefined') {
  globalThis.importMetaUrl = self.location ? self.location.href : 'https://localhost:3000/';
}
`,
  },
  logLevel: 'info',
  plugins: [
    {
      name: 'import-meta-url',
      setup(build) {
        build.onLoad({ filter: /\.js$/ }, async (args) => {
          const fs = await import('fs');
          let contents = await fs.promises.readFile(args.path, 'utf8');
          contents = contents.replace(/import\.meta\.url/g, 'globalThis.importMetaUrl');

          return {
            contents,
            loader: 'js',
          };
        });
      },
    },
  ],
};

async function buildWorkers() {
  try {
    await esbuild.build({
      ...commonBuildOptions,
      entryPoints: ['./app/lib/workers/speech-worker-source.js'],
      outfile: './public/speech-worker-bundled.js',
    });
    console.log('✅ Trained worker bundled successfully!');

    // Build untrained worker
    await esbuild.build({
      ...commonBuildOptions,
      entryPoints: ['./app/lib/workers/speech-worker-untrained.js'],
      outfile: './public/speech-worker-untrained-bundled.js',
    });
    console.log('✅ Untrained worker bundled successfully!');

  } catch (error) {
    console.error('❌ Failed to bundle workers:', error);
    process.exit(1);
  }
}

buildWorkers();